### ISSUE TITLE
An example from synopsis does not work

### ISSUE THREAD

**Issue by KES777** [Corion/WWW-Mechanize-Chrome#22]
the errors are:
```
Use of uninitialized value $cmd[0] in exec at /home/kes/work/projects/tucha/monkeyman/local/lib/perl5/WWW/Mechanize/Chrome.pm line 438.
Can't exec "": No such file or directory at /home/kes/work/projects/tucha/monkeyman/local/lib/perl5/WWW/Mechanize/Chrome.pm line 438.
```

**Comment by KES777** [comment]
resolved as:

```
my $mech = WWW::Mechanize::Chrome->new(
	headless   => 1, # otherwise, PDF printing will not work
	launch_exe => 'chromium-browser',
);
```

**Comment by Corion** [comment]
There certainly is a bug in W:M:Chrome in that it tries an empty executable name when it doesn't find the appropriate browser executable, but if you're not using Chrome but Chromium, you need to specify that explicitly, yes.

I'll leave this report open, because W:M:Chrome should provide a good error message when it doesn't find an appropriate executable at all.
