### ISSUE TITLE
Didn't see a 'Network.responseReceived' event for frameId

### ISSUE THREAD

**Issue by sdondley** [Corion/WWW-Mechanize-Chrome#34]
I'm trying to log into twitter.com automatically. When I try to submit the login form, I get an error:

`Didn't see a 'Network.responseReceived' event for frameId CCFEFDAEDAF4F4BDFBD57DCF85C5B736, requestId 1000091631.28, cannot synthesize response at /Users/me/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.4/WWW/Mechanize/Chrome.pm line 1852.`

Here's the code which is pretty straightforward.

```
  $mech->form_number(1);
  $mech->field('session[username_or_email]' => 'user');
  $mech->field('session[password]' => 'password');
  $mech->click({ selector => "form.LoginForm input.EdgeButton" });  # error occurs here
```

I've tried different ways of submitting the form but without luck.

**Comment by Corion** [comment]
Most likely, this happens because the button click does not trigger a HTTP request/response, but I can't verify that since you didn't post a script that allows me to reproduce the problem.

This does not really seem like a bug and more like a support request Please use https://perlmonks.org for support and the bug tracker only for real bugs.
