### ISSUE TITLE
->update_html halts

### ISSUE THREAD

**Issue by KES777** [Corion/WWW-Mechanize-Chrome#42]
I have next Mojolicious helper:
```
sub html2pdf {
	my $chrome =  shift->chrome;
	my $html =  shift;
	$chrome->update_html( $html );
	return $chrome->content_as_pdf( format => 'A4' );
}
```

it halts execution of script, but if I provide string to `update_html` method, then works fine:

    $chrome->update_html( $html );

How to reproduce:

    $html = '<b>Hi</b>';
    $chrome->update_html( "$html" ); # works
    $chrome->update_html(  $html  ); # halted

**Comment by Corion** [comment]
Most likely, Mojolicious returns an object instead of a plain string. `->update_html` wants a string and you've already found a workaround. I'll add a proper test and fix for this issue, by always stringifying the argument to `->update_html`.

**Comment by KES777** [comment]
This is not mojolicious. See `how to reproduce`. Here `$html` is not object

**Comment by Corion** [comment]
Hmm - but the above code is already how it is tested in https://github.com/Corion/WWW-Mechanize-Chrome/blob/master/t/51-mech-set-content.t (the currently only test). Does that test pass for you?

I'll add your test case to that file as well, but I don't see how it is different. If you can please add a short program like `t/51-mech-set-content.t` to this ticket, and the Chrome version and the module versions as `t/00-load.t` outputs, then I can maybe replicate the problem.

Also, running the script with logging initialized to `$TRACE` instead of `$ERROR` maybe shows where the problems start.

**Comment by Corion** [comment]
Is this issue still open? I've added tests and they always pass for me.

**Comment by KES777** [comment]
I can not reproduce the issue on 0.44 version

**Comment by KES777** [comment]
For reference: commit: 77877ee8
