### ISSUE TITLE
Installation freezes on Windows 10 with Strawbery Perl 5.38.0.1-64bit

### ISSUE THREAD

**Issue by maneatingcow** [Corion/WWW-Mechanize-Chrome#79]
Hello,

My installation stops at 50-tick.t. It gets to 6/18 and then seems to go into an infinite loop.

Is there anything I can do to provide more info?

Thanks.

**Comment by Corion** [comment]
You can run the test in isolation with the log level set to trace and run the test in isolation:

For unixish / Linuxish systems:
```
export TEST_LOG_LEVEL=trace
perl -Ilib t/50-tick.t
```

For Windows:
```
set TEST_LOG_LEVEL=trace
perl -Ilib t/50-tick.t
```

**Comment by maneatingcow** [comment]
[output.txt](https://github.com/Corion/WWW-Mechanize-Chrome/files/14091679/output.txt)

Thanks! Here's what I get. Also I've noticed I get a ton of Chrome processes that never die when doing this command (which I had to run a few times while I re-learned shell redirection).

**Comment by maneatingcow** [comment]
I'm not sure what the polite thing to do in terms of following up here. Is there more I can do? Should I just wait a while?

**Comment by Corion** [comment]
I ran the test suite on a fast machine on Windows and can reproduce the hang there. It certainly is a timing issue, because the problem disappears if I add the following line in `t/50-tick.t`:

` ` ` 
    WWW::Mechanize::Chrome->new(
        autodie => 1,
        @_,
		headless => 0,
    );
` ` ` 

With a displayed browser window, the test failure disappears.

I think you can ignore the test failure but I will look into releasing a newer version of WWW::Mechanize::Chrome that ideally does not have this timing issue.

**Comment by maneatingcow** [comment]
OK I added that and the install worked. Thanks very much for your help!
